#! /bin/bash
# APKMTool 1.0
# ------------------------------------------------
# Modified Apk Multi-Tools
# by mikko3024
# 
# Changelog:
# 
# 2012-09-17
# - Added support for file selection
# - Support for batch APK signing
# 
# 2012-09-18
# - Added adb pull framework-res.apk
# - Device check before ADB operations
# - Set pulled APK as active APK
# - Backup remote APK before ADB push
# - Chmod 644 after ADB push (system APK)
# - Compression level menu (default: 0)
# 
# 2012-09-20
# - Ask if APK to compile is system or regular APK
# - Fix zip compression level implementation
# - Prompt user to set an active APK if not set
# - Make menus consistent
# - Various code rewrite, fixes and typo corrections
#
# 2012-09-23
# - Add settings.conf for storing preferences. (Auto-created)
# - Compression level in settings.conf support
# 
# 2012-09027
# - Start ADB daemon on launch
# 
# 2012-09029
# - Bug Fixes.
# - Menu changes.
# 
# ------------------------------------------------

# 0) Pull APK
ap () {
	if [[ $(stat=$(adb devices); echo ${#stat}) != "25" ]] ; then			# 25 if no device is connected
		echo "Enter APK remote file location:" 
		echo "i.e. /system/app/launcher.apk"
		echo 
		printf "Input: "
		read INPUT
		APK_FILE=`basename $INPUT`
		adb pull "$INPUT" "apk-input/$APK_FILE"
		if [ "$?" -ne "0" ] ; then
			echo "Error: while pulling $APK_FILE"
		fi
		if [[ -f "apk-input/$APK_FILE" ]] ; then
			echo "$APK_FILE copied."
			fileName=${APK_FILE%*.apk}
		fi
	else
		echo ; echo "Error. No device connected."
	fi
}

# 1) Extract APK
ex () {
	echo 
	if [[ -n $fileName ]] ; then
		cd tools
		rm -f "../apk-input/$fileName-signed.apk"
		rm -f "../apk-input/$fileName-unsigned.apk"
		rm -rf "../projects/$fileName.apk"
		if [ ! -d "../projects/$fileName.apk" ] ; then
			mkdir "../projects/$fileName.apk"
		fi
		clear
		# Must be -o"../projects" and not -o "../projects"
		7za x -o"../projects/$fileName.apk" ../apk-input/$fileName.apk
		cd ..
	else
		actvfile ; retval=$? ; if [[ $retval == 0 ]]; then echo $retval ; ex ; fi
	fi
}

# 2) Optimize APK PNGs
opt () {
	echo 
	if [[ -n $fileName || -f ../projects/$fileName.apk/res ]] ; then
		cd tools
		find "../projects/$fileName.apk/res" -name *.png | while read PNG_FILE ;
		do
			if [ `echo "$PNG_FILE" | grep -c "\.9\.png$"` -eq 0 ] ; then
				optipng -o99 "$PNG_FILE"
			fi
		done
		clear
		echo 
		echo "PNGs optimized."
		cd ..
	else
		echo "Error. Check active APK file and if APK is extracted."
	fi
}

pack () {
	cd tools
	7za a -tzip "../apk-input/$fileName-unsigned.apk" ../projects/$fileName.apk/* -mx"$clvl"
	cd ..
}

oa () {
	rm -rf "projects/$fileName.apk/META-INF"
	pack
}

# 3) Zip APK
zip () {
	if [[ -n $fileName ]] ; then
		echo "Enter APK type:"
		echo "---------------"
		list="System-APK Regular-APK"
		PS3=$(echo ; echo "Enter selection: ")
		select mode in $list; do
			case "$mode" in
			"System-APK"  ) pack ; break ;;
			"Regular-APK" ) oa ; break ;;
				*) echo ; echo "Invalid input." ;;
			esac
		done
		clear ; echo ; echo "File: $fileName.apk zipped."
	else
		actvfile ; retval=$? ; if [[ $retval == 0 ]]; then zip ; fi
	fi
}

# 4) Sign APK
si () {
	echo 
	if [[ -n $fileName ]] ; then
		cd tools
		INFILE="../apk-input/$fileName-unsigned.apk"
		projectsFILE="../apk-input/$fileName-signed.apk"
		if [ -e "$INFILE" ] ; then
			#echo "java -jar signapk.jar -w testkey.x509.pem testkey.pk8 $INFILE $projectsFILE"
			java -jar signapk.jar -w testkey.x509.pem testkey.pk8 "$INFILE" "$projectsFILE"
			if [ "x$?" = "x0" ] ; then
				rm -f "$INFILE"
			fi
			echo "Done."
		else
			echo "Warning: cannot find file '$INFILE'"
		fi
		cd ..
	else
		actvfile ; retval=$? ; if [[ $retval == 0 ]]; then si ; fi
	fi
}

# 5) Zipalign
zipa () {
	echo 
	if [[ -n $fileName ]] ; then
		for STRING in "unsigned" "signed"
		do
			if [ -f "apk-input/$fileName-$STRING.apk" ] ; then
				zipalign -fv 4 "apk-input/$fileName-$STRING.apk" "apk-input/$fileName-$STRING-aligned.apk"
				if [ "x$?" = "x0" ] ; then
					mv -f "apk-input/$fileName-$STRING-aligned.apk" "apk-input/$fileName-$STRING.apk"
				fi
			else
				echo "Zipalign: Cannot find file 'apk-input/$fileName-$STRING.apk'"
			fi
		done
		clear ; echo ; echo "Done."
	else
		actvfile ; retval=$? ; if [[ $retval == 0 ]]; then zipa ; fi
	fi
}

# 6) Install APK
ins () {
	clear
	echo 
	if [[ $(stat=$(adb devices); echo ${#stat}) != "25" ]] ; then
		echo "Install APK: $fileName.apk (y/N)?"
		read INPUT
		if [ x$INPUT -e "xy" || x$INPUT -e "xY" ] ; then
			#echo "adb install -r apk-input/$fileName-signed.apk"
			adb install -r "apk-input/$fileName-signed.apk"
		fi
	else
		echo "Error. No device connected."
	fi
}

# 7) Zip / Sign / Install APK
alli () {
	if [[ -n $fileName ]] && [[ $(stat=$(adb devices); echo ${#stat}) != "25" ]] ; then
		echo "Enter APK type:"
		echo "---------------"
		list="System-APK Regular-APK"
		PS3=$(echo ; echo "Enter selection: ")
		select mode in $list; do
			case "$mode" in
				"System-APK"  ) pack ; ins ; break ;;
				"Regular-APK" ) oa ; pack ; si ; ins ; break ;;
					*) echo ; echo "Invalid input." ;;
			esac
		done
	else
		echo ; echo "Error. Check active APK file and make sure device is connected."
	fi
}

# 8)
apu () {
	if [[ -n $fileName ]] && [[ $(stat=$(adb devices); echo ${#stat}) != "25" ]] ; then
		echo "Enter remote APK location."
		echo "i.e. /system/app/launcher.apk "
		echo
		printf "Input: "
		read INPUT
		adb root
		adb remount
		adb shell cp $INPUT $INPUT.backup
		adb push "apk-input/$fileName-unsigned.apk" "$INPUT"
		adb shell chmod 644 $INPUT
	else
		echo "Error. Check active APK file and make sure device is connected."
	fi
}

# 9)
de () {
	if [[ -n $fileName ]] ; then
		cd tools
		rm -f "../apk-input/$fileName-signed.apk"
		rm -f "../apk-input/$fileName-unsigned.apk"
		rm -rf "../projects/$fileName.apk"
		#echo "java -jar apktool.jar d ../apk-input/$fileName.apk ../projects/$fileName.apk"
		java -jar apktoolD.jar d ../apk-input/$fileName.apk "../projects/$fileName.apk"
		cd ..
	else
		echo 
		actvfile ; retval=$? ; if [[ $retval == 0 ]]; then de ; fi
	fi
}

# 10)
co () {
	cochk
	if [[ -n $fileName ]] ; then
		cd tools
		baseAPK=`basename $fileName`
		#echo "java -jar apktool.jar b ../projects/$fileName.apk ../apk-input/$fileName-unsigned.apk"
		java -jar apktoolB.jar b "../projects/$fileName.apk" "../apk-input/$fileName-unsigned.apk"
		cd ..
	else
		actvfile ; retval=$? ; if [[ $retval == 0 ]]; then co ; fi
	fi
	retainorigfiles	
}

cochk () {
	echo "Enter APK type:"
	echo "---------------"
	list="System-APK Regular-APK"
	PS3=$(echo ; echo "Enter selection: ")

	select comptype in $list; do
		case "$comptype" in
			"System-APK"|"Regular-APK" ) break ;; # valid input.
			   *) echo ; echo "Invalid input." ;;
		esac
	done
}

retainorigfiles () {
	echo 
	if [[ $comptype == 1 ]]; then
		echo "Aside from APK signatures, copy unmodified files "
	else
		printf "Copy unmodified files "
	fi
	printf "to compiled APK to reduce errors (Y/n)? "
	read INPUT
	if [[ x$INPUT ==  "xY" || x$INPUT ==  "xy" || x$INPUT ==  "x" ]] ; then
		cd tools
		rm -rf ../keep
		7za x -o"../keep" ../apk-input/$fileName.apk
		if [[ $comptype == 2 ]] ; then
			rm -rf ../keep/META-INF
		fi
		echo 
		echo "Delete all modified files in the /keep directory."
		echo "If you modified an XML file, delete the resources.arsc file."
		echo "Press Enter key to continue."
		read DUMMY
		7za a -tzip "../apk-input/$fileName-unsigned.apk" ../keep/* -mx"$clvl" -r
		rm -rf ../keep
		cd ..
	fi
	clear
	echo 
	echo "Done"
}

# 11)
all () {
	co
	si
	ins
}

# 12)
bopt () {
	cd tools
	mkdir -p "../apk-optimize/original"
	find "../apk-optimize" -name *.apk | while read APK_FILE ;
	do
		echo "Optimizing $APK_FILE"
		# Extract
		7za x -o"../apk-optimize/original" "../apk-optimize/$APK_FILE"
		# PNG
		find "../apk-optimize/original" -name *.png | while read PNG_FILE ;
		do
			if [ `echo "$PNG_FILE" | grep -c "\.9\.png$"` -eq 0 ] ; then
				optipng -o99 "$PNG_FILE"
			fi
		done
		# TODO optimize .ogg files
		# Re-compress
		7za a -tzip "../apk-optimize/temp.zip" ../apk-optimize/original/* -mx"$clvl"
		FILE=`basename "$APK_FILE"`
		DIR=`dirname "$APK_FILE"`
		mv -f "../apk-optimize/temp.zip" "$DIR/optimized-$FILE"
		rm -rf ../apk-optimize/original/*
	done
	rm -rf "../apk-optimize/original"
	cd ..
}

# 13)
asi () {
	echo 
	cd tools
	find "../apk-sign" -name *.apk | while read APK_SIGN ;
	do
		java -jar signapk.jar -w testkey.x509.pem testkey.pk8 $APK_SIGN ${APK_SIGN%.*}-signed.apk
		echo "${APK_SIGN%.*}-signed.apk - Done."
	done
	cd ..
}

# 14)
ogg () {
	cd tools
	mkdir -p "../ogg-optimize"
	find "../ogg-optimize/" -name *.ogg | while read OGG_FILE ;
	do
		FILE=`basename "$OGG_FILE"`
		DIR=`dirname "$OGG_FILE"`
		printf "%s" "Optimizing: $FILE"
		sox "$OGG_FILE" -C 0 "$DIR/optimized-$FILE"
		if [ "x$?" = "x0" ] ; then
			printf "\n"
		else
			printf "...%s\n" "Failed"
		fi
	done
}

# 15)
selt () {
	cd apk-input
	echo 
	echo "Listing APK files:"
	echo "------------------"
	PS3=$(echo ""; echo "Choose APK: ")
	fileList=$(find -type f -name "*.apk")
	# Clean up list.
	fileList=${fileList//"./"/}

	if [[ -z $fileList ]] ; then
		clear
		echo ; echo "No APK files found. Please check the apk-input directory."
		return 1
	else
		select fileName in $fileList; do
			if [[ -n "$fileName" ]] ; then
				fileName=${fileName%.*}
				if [[ $1 == "s1" ]]; then clear ; fi
					echo ; echo "Selected: $fileName.apk" ; break
					return 0
			else
		    	echo ; echo "Error. Wrong input."
		    	return 1
		    fi
		done
	fi


	cd ..
}

actvfile () {
	echo "No active APK file set."
	printf "Set active APK file? (Y/n): "
	read INPUT
	if [[ x$INPUT == "xy" || x$INPUT == "xY" || x$INPUT == "x" ]]; then
		selt ; retval=$? ; if [[ $retval == 1 ]]; then
			echo "Operation aborted."
			return 1
		else
			return 0
		fi
	else
		clear ; echo ; echo "Operation aborted."
		return 1
	fi
}

# 16)
frm () {
	rm -rf $HOME/apktool
	cd tools
	printf "Pull framework-res.apk from an ADB device (Y/n)? "
	read INPUT
	if [[ x$INPUT == "xY" || x$INPUT == "xy" || x$INPUT == "x" ]] ;  then
		if [[ $(stat=$(adb devices); echo ${#stat}) != "25" ]] ; then
			echo 
			echo "Pulling framework-res.apk from device."
			adb pull /system/framework/framework-res.apk ./framework-res.apk
			#adb pull /system/framework/framework-res.apk $HOME/apktool/framework/1.apk
			java -jar apktool.jar "if" ./framework-res.apk
		else
			echo "Error. No device connected."
		fi
	fi
	cd ..
}

# 17)
clr () {
	printf "Do you want to clean your current projects (y/N)? "
	read INPUT
	if [[ "x$INPUT" = "xy" || "x$INPUT" = "xY" ]] ; then
		rm -rf apk-sign
		rm -rf projects
		rm -rf apk-optimize
		mkdir apk-sign
		mkdir apk-optimize
		echo "Projects cleared."
		echo 
		printf "Clear apk-input directory (y/N)? "
		read INPUT
		if [[ "x$INPUT" = "xy" || "x$INPUT" = "xY" ]] ; then
			echo "Directory apk-input cleared."
			rm -rf apk-input
			mkdir apk-input
			fileName=""
		fi
		echo 
		printf "Delete framework-res.apk import (y/N)? "
		read INPUT
		if [[ "x$INPUT" = "xy" || "x$INPUT" = "xY" ]] ; then
			echo "File framework-res.apk deleted."
			rm -rf $HOME/apktool
		fi
	else
		echo "Canceled."
	fi
}

# 20)
setclv () {
	echo "Current compression level: $clvl"
	printf "Enter new compression level (Value 0-9): "
	read INPUT
	echo 
	case "$INPUT" in
		0|1|2|3|4|5|6|7|8|9 )
			clvl=$INPUT
			sed -i "1s/compressionLevel=.*/compressionLevel=$INPUT/g" "$confFile"
			echo "Compression level set at: $clvl"
		;;

		*)  echo "Invalid value."
		;;
	esac
}

# 00)
quit () {
	exit 0
}

restart () {
	echo 
	echo "############################### Apk Multi-Tool ################################"
	echo 
	echo "- Simple Tasks (Image editing, etc.) ------------------------------------------"
	echo "  1    Extract APK                       2    Optimize APK Images              "
	echo "  3    Zip APK                                                                 "
	echo "  7    One-step Zip-Sign-Install"
	echo 
	echo "- Advanced Tasks (XML, Smali, etc.) -------------------------------------------"
	echo "  9    Decompile APK                     10   Compile APK                      "
	echo "  11   One-step Compile-Sign-Install"
	echo 
	echo "- Common Tasks ----------------------------------------------------------------"
	echo "  0    ADB Pull                          8    ADB Push                         "
	echo "  4    Sign APK                          6    Install APK                      "
	echo "  5    Zipalign APK                                                            "
	echo 
	echo "- Batch Operations ------------------------------------------------------------"
	echo "  12   Batch Optimize APK                13 Batch Sign APK                     "
	echo "  14   Batch Optimize ogg files"
	echo 
	echo "-------------------------------------------------------------------------------"
	echo "  15   Set Active APK"
	echo "  16   Import framework-res.apk  (Perform apktool.jar if framework-res.apk)"
	echo "  17   Clear Project Files"
	echo "  20   Set Compression Level     (Current compression level: $clvl)"
	echo "  00   Quit"
	echo "-------------------------------------------------------------------------------"
	printf "  Active APK File: "
	if [[ -n $fileName ]] ; then
		printf "$fileName.apk"
	else
		printf "NONE"
	fi
	printf "\n"
	echo "-------------------------------------------------------------------------------"
	echo 
	printf "%s" "Enter selection: "
	read ANSWER
	reset
	case "$ANSWER" in
		 0)       ap ;;
		 1)       ex ;;
		 2)      opt ;;
		 3)      zip ;;
		 4)       si ;;
		 5)     zipa ;;
		 6)      ins ;;
		 7)     alli ;;
		 8)      apu ;;
		 9)       de ;;
		10)       co ;;
		11)      all ;;
		12)     bopt ;;
		13)      asi ;;
		14)      ogg ;;
		15)     selt "s1" ;; # Set via menu
		16)      frm ;;
		17)      clr ;;
		20)   setclv ;;
		"00")   quit ;;
		 *)
			echo "Unknown command: '$ANSWER'"
		;;
	esac
}

# Start ----------------------------------------
# Terminal Dimensions
printf '\033[8;48;80t'
PATH="$PATH:$PWD/tools"
reset

# Defaults
fileName=""	# Active APK File
confFile=settings.conf 	# Config File

# Config File Check
if [[ ! -f ./$confFile ]]; then
	clvl="0"	# Compression Level - Default value
	echo "compressionLevel=0" >> settings.conf
else
	setprs=$(sed -n "1p" "$confFile")
	clvl=${setprs##*=}
fi

clear
export PATH
#echo $PATH

# Test for needed programs and warn if missing
ERROR="0"
for PROGRAM in "optipng" "7za" "java" "sudo" "adb" "aapt" "sox"
do
	which "$PROGRAM" > /dev/null 
	if [ "x$?" = "x1" ] ; then
		ERROR="1"
		echo "The program $PROGRAM is missing or is not in your PATH,"
		echo "please install it or fix your PATH variable"
	fi
done
if [ "x$ERROR" = "x1" ] ; then
	exit 1
fi

adbd=$(adb start-server)	# Start ADB Daemon

clear
while [ "1" = "1" ] ;
do
	restart
done
exit 0